version: '3.4'

services:
  postgres:
    image: postgres:latest
    volumes:
      - persistent-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  app:
    build:
      context: .
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SERVER_IP=0.0.0.0
      - SERVER_PORT=${SERVER_PORT}
      - NODE_ENV=production
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    command: "./start.sh"

volumes:
  persistent-data: